### ISSUE TITLE
please include LICENSE files in repo + published crates

### ISSUE THREAD

**Issue by decathorpe** [addr-rs/psl-types#2]
I am working on packaging this crate for Fedora Linux, since it is now pulled in by reqwest 0.11.7 → cookie_store 0.15.1 → publicsuffix 2.1.1 → psl-types 2.0.9, but I have noticed that neither published crates nor the git repository for psl-types includes LICENSE-MIT / LICENSE-APACHE files.

Since both those licenses require that license text is included with redistributed sources, please include them here and in future versions of this crate that will be published to crates.io.

**Comment by rushmorem** [comment]
Done. Thank you.

**Comment by decathorpe** [comment]
Thanks for the quick response! :+1:
